# This file uses TOML syntax
# https://github.com/toml-lang/toml

# If using sublime text for syntax highlight do the following
# cd ~/.config/sublime-text-3/Packages
# git clone https://github.com/Gakai/TOML

# For private settings you'll need a .valkyrja.user.toml
# Any settings in it will be merged into this file

autogroup = true # auto-add chgrp command

[servers]

	[servers.defaults]
	build = "production"
	check = "all"
	group = "www-data"

	# For multi-server categories you can use both array and hashes. You will
	# need hashes if you want private configuration per server in category.

	[[servers.development]]
	build = false
	check = false
	title = "Sjöfn"
	host  = "your.private.server"
	path  = "/var/www/project/1.x"
	group = "apache"

	[servers.test.local]
	title = "Eir"
	host  = "localhost"
	path  = "~/example/staging"

[postdeploy]

	# commands will be executed after every deploy
	# cwd will be set to the server path

	defaults = [
		# options for all categories
	]

	development = [
		# empty
	]

	staging = [
		# empty
	]

	production = [
		# empty
	]

[rsync]

	# please see rsync man page for options

	verbose = true         # show files transfered
	delete = true          # delete extraneous files from dest dirs
	checksum = true        # skip based on checksum, not mod-time & size
	recursive = true       # recurse into directories
	executability = true   # preserve executability
	links = true           # copy symlinks as symlinks
	safe-links = true      # ignore symlinks that point outside the tree
	inplace = true         # update destination files in-place
	compress = true        # compress file data during the transfer
	human-readable = true  # output numbers in a human-readable format

	exclude = [
		".valkyrja.*",
		".git*",
		".hg",
		".svn",
		".CVS",
		".idea",
		"*.log",
		"*~",
		"*.tar.bz2",
		"*.tgz",
		".DS_Store",
		"Thumbs.db"
	]

	include = [
		# empty
	]

	patterns = [
		# empty
	]

[ssh]

	stop-on-error = false
	timeout = 600000 # ms (10min)
